type: polarArea
data:
  labels:
    - Red
    - Green
    - Yellow
    - Grey
    - Blue
  datasets:
    - data: [11, 16, 7, 3, 14]
      backgroundColor:
        - rgba(255, 99, 132, 0.8)
        - rgba(75, 192, 192, 0.8)
        - rgba(255, 206, 86, 0.8)
        - rgba(201, 203, 207, 0.8)
        - rgba(54, 162, 235, 0.8)
options:
  plugins:
    legend:
      position: right
    title:
      display: true
      text: Polar Area Chart
